export const FIND_EVENTS = "FIND_EVENTS"

export const LOAD_EVENTS = "LOAD_EVENTS"

export const OWNER_EVENTS = "OWNER_EVENTS"

export const ADD_FAVORITE = "ADD_FAVORITE"

export const PARTICIPE_EVENT = "PARTICIPE_EVENT"

export const CREATE_EVENT = "CREATE_EVENT"