export const FIND_EVENTS = "FIND_EVENTS"

export const FIND_CURRENT_EVENTS = "FIND_CURRENT_EVENTS"

export const LOAD_EVENTS = "LOAD_EVENTS"

export const OWNER_EVENTS = "OWNER_EVENTS"

export const ADD_FAVORITE = "ADD_FAVORITE"

export const PARTICIPE_EVENT = "PARTICIPE_EVENT"

export const CREATE_EVENT = "CREATE_EVENT"

export const SET_ORGANISATION = "SET_ORGANISATION"

export const SET_PARTICIPATION = "SET_PARTICIPATION"

export const ACCEPT_PARTICIPATION = "ACCEPT_PARTICIPATION"

export const REFUSE_PARTICIPATION = "REFUSE_PARTICIPATION"

export const CANCEL_PARTICIPATION = "CANCEL_PARTICIPATION"

export const PAY_PARTICIPATION = "PAY_PARTICIPATION"

export const CANCEL_EVENT = "CANCEL_EVENT"

export const FINISH_EVENT = "FINISH_EVENT"